version: '3.8'

services:
  node-app:
    image: node:21.7.3
    container_name: relation_builder
    ports:
      - "3000:3000" 
    volumes:
      - .:/app 
    working_dir: /app
    command: sh -c "npm install && npm run start" 
    environment:
      - NODE_ENV=development
